version: '3'
services:
  node-app:
    build: ./rhythmoji-app
    links:
      - "flask-app"
    depends_on:
      - flask-app
    networks:
      - mynet
    ports:
      - "3000:3000"
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - OPEN_AI_KEY=${OPEN_AI_KEY}

  flask-app:
    build: ./background-removal-app
    ports:
      - "5001:5001"
    networks:
      - mynet

networks:
  mynet:

