services:
  # Node App Configuration (Public)
  - type: web
    name: node-app
    runtime: docker
    dockerCommand: docker-compose -f docker-compose.yml up node-app

  # Flask App Configuration (Private)
  - type: pserv
    name: flask-app
    runtime: docker
    dockerCommand: docker-compose -f docker-compose.yml up flask-app
